cache:
  directories:
    - $HOME/.m2
language: java

jdk: openjdk8

name: Codecov
uses: codecov/codecov-action@v3.0.0


sudo: false
script:
  - java -version
  - mvn clean install
  - mvn clean package
  - mvn test
  - bash <(curl -s https://codecov.io/bash)

#after_success:
